import { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
} from "react-icons/pi";

import {
  SiLinux,
  SiDocker,
  SiJavascript,
  SiNextdotjs,
  SiNodedotjs,
  SiLaravel,
  SiCodeigniter,
  SiPhp,
  SiCss,
  SiHtml5,
  SiTailwindcss,
  SiBootstrap,
  SiMysql,
  SiPostgresql,
  SiMinio,
  SiRedis,
  SiSwagger,
  SiGit,
  SiBitbucket,
  SiGnubash,
  SiKubernetes,
  SiJenkins,
  SiGithubactions,
  SiSonarqubeserver,
  SiTerraform,
  SiGrafana,
  SiPrometheus,
  SiOpentelemetry,
} from "react-icons/si";

import {
  FaDiscord,
  FaGithub,
  FaLinkedin,
  FaX,
  FaXTwitter,
  FaFacebook,
  FaWhatsapp,
  FaTelegram,
  FaInstagram,
  FaTiktok,
  FaGolang,
  FaLinux,
  FaDocker,
} from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  x: FaX,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  linux: SiLinux,
  docker: SiDocker,
  javascript: SiJavascript,
  nodejs: SiNodedotjs,
  nextjs: SiNextdotjs,
  laravel: SiLaravel,
  codeigniter: SiCodeigniter,
  php: SiPhp,
  css: SiCss,
  html5: SiHtml5,
  tailwindcss: SiTailwindcss,
  bootstrap: SiBootstrap,
  mysql: SiMysql,
  postgresql: SiPostgresql,
  golang: FaGolang,
  minio: SiMinio,
  redis: SiRedis,
  swagger: SiSwagger,
  git: SiGit,
  bitbucket: SiBitbucket,
  bash: SiGnubash,
  kubernetes: SiKubernetes,
  jenkins: SiJenkins,
  githubActions: SiGithubactions,
  sonarqube: SiSonarqubeserver,
  terraform: SiTerraform,
  grafana: SiGrafana,
  prometheus: SiPrometheus,
  opentelemetry: SiOpentelemetry,
  github: FaGithub,
  linkedin: FaLinkedin,
  email: HiEnvelope,
  whatsapp: FaWhatsapp,
  telegram: FaTelegram,
  facebook: FaFacebook,
  instagram: FaInstagram,
  twitter: FaXTwitter,
  tiktok: FaTiktok,
  discord: FaDiscord,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
